### ISSUE TITLE
Greyed out elements in inspector after a css reload on Firefox 54

### ISSUE THREAD

**Issue by bendjm** [StoyanDimitrov/css-reload#1]
I think the addon is broken in last Firefox version (54 atm). Some elements are greyed out and aren't selectable after a CSS reload. Steps to reproduce:

1. Open the developer tools.
2. Change your CSS (or not).
3. Make a CSS reload.
4. Try to select some elements with the selector tool or the inspect option from de context menu.

Could you confirm the issue?

**Comment by StoyanDimitrov** [comment]
Can not reproduce with clean profile on Fx54 and Fx56.

**Comment by bendjm** [comment]
Will try with clean profile and verify possible addon conflict asap.

**Comment by StoyanDimitrov** [comment]
Very much appreciated!

**Comment by yurigoytacaz** [comment]
I've had the same problem but find out that it wasn't the CSS Reloader the one to blame, but the FF54, I tried disabling CSS Reloader and the problem (grayed elements in inspect) still happaned (after reloading the page with the inspector open).

But I'm here to ask if there's a way to change the keyboard shortcut to the CSS Reload? (sorry to post this on this thread).

**Comment by StoyanDimitrov** [comment]
Sure, it is possible. Can I ask you to file a separate issue for that?

On 21 June 2017 18:38:42 EEST, Yuri Goytacaz <notifications@github.com> wrote:
>I've had the same problem but find out that it wasn't the CSS Reloader
>the one to blame, but the FF54, I tried disabling CSS Reloader and the
>problem (grayed elements in inspect) still happaned (after reloading
>the page with the inspector open).
>
>But I'm here to ask if there's a way to change the keyboard shortcut to
>the CSS Reload? (sorry to post this on this thread).
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/StoyanDimitrov/css-reload/issues/1#issuecomment-310118990

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bendjm** [comment]
@yurigoytacaz I confirm, the issue is not related to CSS Reloader but Firefox 54 (tested with a clean install). You can see multiples CSS, XHTML and JS errors in the navigator console (Ctrl+Maj+J) related to the inspector when the bug happens. Let me know if you find out a solution.

@StoyanDimitrov Sorry for the trouble and thank you for looking at it.

**Comment by StoyanDimitrov** [comment]
Thanks for having a look into it.
