### ISSUE TITLE
Add an option to also reload images

### ISSUE THREAD

**Issue by jehon** [StoyanDimitrov/css-reload#6]
Hello

Thanks for your great plugin.

Could you also reload the pictures?

I am thinking about something like
<img src='myImage.jpg'> ==> <img src='myImage.jpg?nocache=123'>

It would help when modifying pictures.

Thanks

**Comment by StoyanDimitrov** [comment]
It's, of course, doable but beyond the scope of this extension. Probably a separate one. It'll work with the assumption of all images being inline. Which is rarely the case. Might worth a shot.
