### ISSUE TITLE
Reload userContent.css

### ISSUE THREAD

**Issue by gjs---** [StoyanDimitrov/css-reload#9]
Hello --

Thank you for making this extension available.

Currently css-reload does not seem to reload **chrome/userContent.css** from the Firefox user's profile.  Would that be possible, perhaps controlled by an on/off option?  

Right not the only way to reload **userContent.css** is to restart Firefox, which becomes tiresome after the first five or six experiments.

-- Thanks

**Comment by StoyanDimitrov** [comment]
Hey,
that one can not be reloaded via Browser Extension API's, unfortunately.

**Comment by krystian3w** [comment]
Try move to StyloaiX https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/chrome

Should works with: https://github.com/Aris-t2/CustomJSforFx/tree/master/script_loader or https://github.com/MrOtherGuy/fx-autoconfig
